// frontend/src/pages/Article/components/DeleteCommentModal.tsx
import { useState, type Dispatch, type SetStateAction } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { ActionButton } from '../../../components/ActionButton'
import { Modal } from '../../../components/Modal'
import { CommentsService } from '../../../services/comments.service'
import type { Comment } from '../../../../../backend/api/database/types'

export function DeleteCommentModal({
	setIsModalOpen,
	comment
}: {
	setIsModalOpen: Dispatch<SetStateAction<boolean>>
	comment: Comment
}) {
	const queryClient = useQueryClient()
	const [loading, setLoading] = useState<boolean>(false)

	const handleDelete = async () => {
		try {
			setLoading(true)
			await CommentsService.delete(comment.id)

			queryClient.invalidateQueries({
				queryKey: ['comments', comment.articleId]
			})
		} catch (error) {
			console.error(error)
		} finally {
			setLoading(false)
		}
	}

	return (
		<Modal>
			<div className='p-6 mobile:w-[80vw] space-y-5 tablet:w-[40vw] bg-brand-blue rounded-2xl'>
				<h2 className='text-white text-6xl font-title'>
					¿Querés eliminar el comentario?
				</h2>

				<div className='space-x-6'>
					<button
						type='button'
						className='px-3 py-4 text-2xl bg-brand-orange clickable rounded text-white font-bold'
						onClick={() => setIsModalOpen(false)}
					>
						Cancelar
					</button>

					<ActionButton
						className='px-3 py-4 text-2xl text-white font-bold bg-brand-red'
						onClick={handleDelete}
						loading={loading}
					>
						Eliminar
					</ActionButton>
				</div>
			</div>
		</Modal>
	)
}

// src/lib/features/comments/client/components/DeleteCommentModal.svelte
<script lang="ts">
import Button from 'client/components/Button.svelte'
import ErrorMessage from 'client/components/ErrorMessage.svelte'
import Modal from 'client/components/Modal.svelte'
import { HttpService } from 'client/services/http.service'

const {
	isOpen,
	close,
	commentId,
	onCommentDeleted
}: {
	commentId: string
	close: () => void
	isOpen: boolean
	onCommentDeleted: (commentId: string) => void
} = $props()
let error = $state<string | undefined>()

async function onDelete() {
	try {
		const success = await HttpService.delete<boolean>({
			url: `/api/comments/${commentId}`
		})

		if (success) {
			onCommentDeleted(commentId)
			close()
		} else {
			error = 'Error al eliminar comentario'
		}
	} catch (err) {
		console.error('[DeleteCommentModal]', err)

		error = 'Error al eliminar comentario'
	}
}
</script>

{#if isOpen}
    <Modal
        {close}
        name="¿Querés borrar este comentario?"
        class="mobile:w-[90vw] tablet:w-[40vw]"
    >
        <ErrorMessage value={error} />

        <div class="space-x-6">
            <Button variant="danger" onclick={onDelete}>Eliminar</Button>
            <Button onclick={close}>Cancelar</Button>
        </div>
    </Modal>
{/if}
