// frontend/src/lib/components/Header.svelte
<script lang="ts">
	import notievanLogoImage from '../assets/images/notievan-logo.webp';
	import HeaderLink from './HeaderLink.svelte';
	import InstagramIcon from './icons/InstagramIcon.svelte';
	import { ARTICLE_WRITER_ROLES } from 'shared/configuration/article-writer-roles.configuration';
	import type { UserOut } from 'shared/dtos/out/user-out.dto';
	import { ROUTES } from '$lib/configuration/routes.configuration';

	const { user }: { user: UserOut | null } = $props();
</script>

<header
	class="sticky top-0 left-0 z-20 flex h-20 w-full items-center justify-center
         bg-linear-to-r from-brand-blue to-[#0d3ea8] drop-shadow-2xl"
>
	<div
		class="flex w-full max-w-317.5 min-w-[320px] items-center justify-between gap-x-1.25 text-2xl text-white mobile:px-4 tablet:px-10 desktop:px-0"
	>
		<nav class="flex items-center mobile:gap-x-3 desktop:gap-x-10" id="header-buttons">
			<HeaderLink href={ROUTES.Home}>
				<img class="aspect-square max-w-13" alt="Logo de NotiEvan" src={notievanLogoImage} />
			</HeaderLink>

			{#if user}
				<HeaderLink href={ROUTES.Account}>Cuenta</HeaderLink>

				{#if ARTICLE_WRITER_ROLES.includes(user.role)}
					<HeaderLink href={ROUTES.CreateArticle}>Crear</HeaderLink>
				{/if}

				{#if user.role === 'ADMIN'}
					<HeaderLink href={ROUTES.Users}>Usuarios</HeaderLink>
				{/if}
			{:else}
				<HeaderLink href={ROUTES.SignIn}>Ingresar</HeaderLink>
			{/if}
		</nav>

		<HeaderLink
			class="mobile:scale-90 desktop:scale-100"
			ariaLabel="Instagram"
			href="https://www.instagram.com/noti.evan"
			target="_blank"
		>
			<InstagramIcon />
		</HeaderLink>
	</div>
</header>

// frontend/src/components/Header.tsx
import notievanLogoImage from '../assets/images/notievan-logo.webp'
import { INSTAGRAM } from '../configuration/information.configuration'
import { useSession } from '../hooks/use-session.hook'
import { HeaderLink } from './HeaderLink'
import { InstagramIcon } from './icons/InstagramIcon'

export function Header() {
	const { user } = useSession()

	return (
		<header
			className='w-full fixed z-20 top-0 left-0 h-20 flex items-center justify-center
         bg-linear-to-r from-brand-blue to-[#0d3ea8] drop-shadow-2xl'
		>
			<div className='w-full gap-x-[5px] text-white mobile:px-3 desktop:px-0 text-2xl max-w-[1270px] min-w-[320px] flex justify-between items-center'>
				<nav
					className='flex items-center desktop:gap-x-10 mobile:gap-x-[25px]'
					id='header-buttons'
				>
					<HeaderLink href='/'>
						<img
							className='max-w-13 aspect-square'
							alt='Logo de NotiEvan'
							src={notievanLogoImage}
						/>
					</HeaderLink>

					{user ? (
						<>
							<HeaderLink href='/cuenta'>Cuenta</HeaderLink>
							{['AUTHOR', 'ADMIN'].includes(user?.role) && (
								<HeaderLink href='/articulos/nuevo'>Crear</HeaderLink>
							)}
						</>
					) : (
						<HeaderLink href='/registro'>Ingresar</HeaderLink>
					)}
				</nav>

				<HeaderLink
					className='mobile:scale-90 desktop:scale-100'
					aria-label='Instagram'
					href={INSTAGRAM}
					target='_blank'
				>
					<InstagramIcon />
				</HeaderLink>
			</div>
		</header>
	)
}
