// frontend/src/lib/components/ImageInput.svelte
<script lang="ts">
	import Button from './Button.svelte';
	import compressFile, { type Options } from 'browser-image-compression';

	interface Props {
		maxSizeMB?: Options['maxSizeMB'];
		maxWidthOrHeight?: Options['maxWidthOrHeight'];
		fileType?: Options['fileType'];
		oninput: (image: File | string) => void;
		value?: string;
	}

	const {
		maxSizeMB = 0.3,
		maxWidthOrHeight = 1200,
		fileType = 'image/webp',
		oninput,
		value: initialValue = ''
	}: Props = $props();

	let imageMode = $state<'url' | 'file'>('url');
	let preview = $state<string>('');
	let loading = $state<boolean>(false);

	$effect(() => {
		if (initialValue) {
			preview = initialValue;
			imageMode = 'url';
		}
	});

	async function onSelectFile(event: Event) {
		const target = event.target as HTMLInputElement;
		const selectedFile = target.files?.[0];

		if (!selectedFile) {
			return;
		}

		loading = true;

		try {
			const compressedFile = await compressFile(selectedFile, {
				maxSizeMB,
				maxWidthOrHeight,
				useWebWorker: true,
				fileType
			});
			const previewUrl = URL.createObjectURL(compressedFile);
			preview = previewUrl;

			const file = new File([compressedFile], 'image.webp', {
				type: 'image/webp'
			});

			oninput(file);
		} catch (err) {
			console.error('Error al procesar imagen', err);
		} finally {
			loading = false;
		}
	}

	function onSelectUrl(event: Event) {
		const target = event.target as HTMLInputElement;
		preview = target.value;

		oninput(target.value);
	}
</script>

<div class="flex w-75 flex-col gap-y-2">
	<header class="mb-2 flex gap-2">
		<Button
			class="flex-1 rounded-md px-4 py-2 text-[1.2rem] font-semibold"
			variant={imageMode === 'url' ? 'default' : 'unselected'}
			onclick={() => {
				imageMode = 'url';
				preview = '';
			}}
		>
			Usar URL
		</Button>

		<Button
			class="flex-1 rounded-md px-4 py-2 text-[1.2rem] font-semibold"
			variant={imageMode === 'file' ? 'default' : 'unselected'}
			onclick={() => {
				imageMode = 'file';
				preview = '';
			}}
		>
			Subir archivo
		</Button>
	</header>

	<main class="flex flex-col gap-2">
		{#if imageMode === 'url'}
			<input
				type="url"
				placeholder="Pegá la URL de la imagen"
				class="rounded-md border bg-white p-2"
				value={preview}
				oninput={onSelectUrl}
			/>

			{#if preview}
				<img
					src={preview}
					alt="Vista previa"
					class="aspect-video max-h-100 w-full max-w-75 rounded-md border border-gray-300 object-cover"
				/>
			{:else}
				<div
					class="aspect-video max-h-100 w-full max-w-75 rounded-md border border-gray-300 bg-brand-gray object-cover"
				></div>
			{/if}
		{:else}
			<input type="file" id="image-input" accept="image/*" class="hidden" oninput={onSelectFile} />

			<label for="image-input" class="flex cursor-pointer flex-col gap-y-2">
				<div class="aspect-video max-h-100 max-w-75 bg-gray-200">
					{#if loading}
						<div class="flex h-full w-full items-center justify-center">
							<span class="text-gray-500">Procesando...</span>
						</div>
					{:else if preview}
						<img src={preview} alt="Vista previa" class="h-full w-full object-cover" />
					{:else}
						<div
							class="flex aspect-video max-h-100 w-full max-w-75 items-center justify-center rounded-md border border-gray-300 bg-brand-gray object-cover text-2xl text-white"
						>
							Click para elegir portada
						</div>
					{/if}
				</div>
			</label>
		{/if}
	</main>
</div>

// frontend/src/components/ImageInput.tsx
import imageCompression from 'browser-image-compression'
import { type ChangeEvent, useState } from 'react'

export function ImageInput({
	onImageSelected,
	value
}: {
	onImageSelected: (image: string | File) => void
	value?: string | File
}) {
	const [preview, setPreview] = useState<string>(
		typeof value === 'string' ? value : ''
	)
	const [imageMode, setImageMode] = useState<'file' | 'url'>('file')
	const [loading, setLoading] = useState(false)

	const onFileChange = async (event: ChangeEvent<HTMLInputElement>) => {
		const selectedFile = event.target.files?.[0]
		if (!selectedFile) {
			return
		}

		setLoading(true)

		try {
			const options = {
				maxSizeMB: 0.3,
				maxWidthOrHeight: 1200,
				useWebWorker: true,
				fileType: 'image/webp'
			}

			const compressedFile = await imageCompression(selectedFile, options)

			const previewUrl = URL.createObjectURL(compressedFile)
			setPreview(previewUrl)

			const file = new File([compressedFile], 'image.webp', {
				type: 'image/webp'
			})

			onImageSelected(file)
		} catch (err) {
			console.error('Error al procesar imagen', err)
		} finally {
			setLoading(false)
		}
	}

	const onUrlChange = (event: ChangeEvent<HTMLInputElement>) => {
		const value = event.currentTarget.value

		setPreview(value)
		onImageSelected(value)
	}

	return (
		<div className='w-[300px] flex flex-col gap-y-2'>
			<header className='flex gap-2 mb-2'>
				<button
					type='button'
					className={`flex-1 py-2 px-4 clickable rounded-md font-semibold ${
						imageMode === 'file' ? 'bg-brand-orange text-white' : 'bg-gray-200'
					}`}
					onClick={() => {
						setImageMode('file')
						setPreview('')
					}}
				>
					Subir archivo
				</button>

				<button
					type='button'
					className={`flex-1 py-2 px-4 clickable rounded-md font-semibold ${
						imageMode === 'url' ? 'bg-brand-orange text-white' : 'bg-gray-200'
					}`}
					onClick={() => {
						setImageMode('url')
						setPreview('')
					}}
				>
					Usar URL
				</button>
			</header>

			{imageMode === 'file' ? (
				<main>
					<input
						type='file'
						id='image-input'
						accept='image/*'
						className='hidden'
						onChange={onFileChange}
					/>

					<label
						htmlFor='image-input'
						className='cursor-pointer flex flex-col gap-y-2'
					>
						<div className='max-h-[400px] max-w-[300px] aspect-video bg-gray-200'>
							{loading ? (
								<div className='w-full h-full flex items-center justify-center'>
									<span className='text-gray-500'>Procesando...</span>
								</div>
							) : preview ? (
								<img
									src={preview}
									alt='Vista previa'
									className='w-full h-full object-cover'
								/>
							) : (
								<div className='w-full h-full flex items-center justify-center'>
									<span className='text-gray-500 text-lg text-center p-4'>
										Clickeá para elegir la portada
									</span>
								</div>
							)}
						</div>
					</label>
				</main>
			) : (
				<main className='flex flex-col gap-2'>
					<input
						type='url'
						placeholder='Pegá la URL de la imagen'
						className='border rounded-md p-2'
						value={preview}
						onChange={onUrlChange}
					/>

					{preview && (
						<img
							src={preview}
							alt='Vista previa'
							className='w-full max-h-[400px] max-w-[300px] aspect-video rounded-md object-cover border border-gray-300'
						/>
					)}
				</main>
			)}

			<footer className='text-sm text-gray-700 text-center'>
				Se recomienda usar imágenes de 1200x675
			</footer>
		</div>
	)
}
