// frontend/src/pages/Article/components/DeleteArticleModal.tsx
import { useState, type Dispatch, type SetStateAction } from 'react'
import { useLocation } from 'wouter'
import { ArticlesService } from '../../../services/articles.service'
import { useQueryClient } from '@tanstack/react-query'
import { ActionButton } from '../../../components/ActionButton'
import { Modal } from '../../../components/Modal'
import type { Article } from '../../../../../backend/api/database/types'

export function DeleteArticleModal({
	setIsModalOpen,
	article
}: {
	setIsModalOpen: Dispatch<SetStateAction<boolean>>
	article: Article
}) {
	const queryClient = useQueryClient()
	const [, setLocation] = useLocation()
	const [loading, setLoading] = useState<boolean>(false)

	const handleDelete = async () => {
		try {
			setLoading(true)
			await ArticlesService.delete(article.id)

			setLocation('/')

			queryClient.invalidateQueries({ queryKey: ['article', article.id] })
			queryClient.invalidateQueries({
				predicate: ({ queryKey }) =>
					Array.isArray(queryKey) && queryKey[0] === 'articles'
			})
		} catch (error) {
			console.error(error)
		} finally {
			setLoading(false)
		}
	}

	return (
		<Modal>
			<div className='p-6 mobile:w-[80vw] space-y-5 tablet:w-[40vw] bg-brand-blue rounded-2xl'>
				<h2 className='text-white text-6xl font-title'>
					¿Querés eliminar el artículo: "{article.title}"?
				</h2>

				<div className='space-x-6'>
					<button
						type='button'
						className='px-3 py-4 text-2xl bg-brand-orange clickable rounded text-white font-bold'
						onClick={() => setIsModalOpen(false)}
					>
						Cancelar
					</button>

					<ActionButton
						className='px-3 py-4 text-2xl text-white font-bold bg-brand-red'
						onClick={handleDelete}
						loading={loading}
					>
						Eliminar
					</ActionButton>
				</div>
			</div>
		</Modal>
	)
}

// frontend/src/routes/articles/[id]/DeleteArticleModal.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import Button from '$lib/components/Button.svelte';
	import ErrorMessage from '$lib/components/ErrorMessage.svelte';
	import Modal from '$lib/components/Modal.svelte';
	import { ClientApiService } from '$lib/services/client-api.service';

	const {
		isOpen,
		close,
		articleId
	}: {
		articleId: string;
		close: () => void;
		isOpen: boolean;
	} = $props();
	let error = $state<string | undefined>();

	async function onDelete() {
		try {
			const success = await ClientApiService.delete<boolean>({ url: `/articles/${articleId}` });

			if (success) {
				goto(resolve('/', {}));
				close();
			} else {
				error = 'Error al eliminar artículo';
			}
		} catch (err) {
			console.error('[DeleteArticleModal]', err);

			error = 'Error al eliminar artículo';
		}
	}
</script>

{#if isOpen}
	<Modal {close} name="¿Querés borrar este artículo?" class="mobile:w-[90vw] tablet:w-[40vw]">
		<ErrorMessage value={error} />

		<div class="space-x-6">
			<Button variant="danger" onclick={onDelete}>Eliminar</Button>
			<Button onclick={close}>Cancelar</Button>
		</div>
	</Modal>
{/if}
