// frontend/src/components/Article.tsx
import type { ArticlePreviewOut } from '../../../shared/src/dtos/out/article-preview-out.dto'
import { useRandomImage } from '../hooks/use-random-image.hook'
import { isRecent } from '../pages/Home/utilities/is-recent.utility'

export function Article({ article }: { article?: ArticlePreviewOut }) {
	const { image } = useRandomImage({
		id: article?.id,
		enabled: !article?.image
	})

	if (!article) {
		return (
			<article className='animate-pulse flex flex-col w-full max-w-[400px] mx-auto'>
				<div className='h-[400px] w-full bg-gray-300 rounded-sm'></div>
				<div className='flex flex-col gap-y-2 w-full mt-4'>
					<div className='h-6 w-3/4 bg-gray-300 rounded' />
					<div className='h-8 w-full bg-gray-300 rounded mt-2' />
					<div className='h-4 w-1/2 bg-gray-300 rounded mt-2' />
				</div>
			</article>
		)
	}

	return (
		<a
			href={`/articulos/${article.id}`}
			className='group clickable block w-full max-w-[400px] mx-auto overflow-hidden'
		>
			<div className='relative w-full aspect-video bg-gray-100 rounded-sm overflow-hidden'>
				{isRecent(article.createdAt) && (
					<div className='absolute top-3 left-3 bg-brand-red text-white text-sm font-bold px-3 py-1 rounded-sm z-10'>
						NUEVO
					</div>
				)}
				<img
					loading='lazy'
					src={article?.image || image}
					alt={article.title}
					className='w-full h-full object-cover'
				/>
			</div>

			<div className='flex flex-col gap-y-2 w-full mt-4'>
				<div className='flex flex-col gap-y-2 w-full'>
					<h4 className='text-brand-red text-3xl wrap-break-word'>
						{article.subtitle}
					</h4>

					<h3 className='text-black font-bold line-clamp-4 text-3xl wrap-break-word'>
						{article.title}
					</h3>

					<p className='text-gray-900 text-[18px] wrap-break-word'>
						{article.description}
					</p>

					<div className='text-gray-700 text-[18px] line-clamp-4 mt-2 wrap-break-word'>
						{article.author.name}
					</div>
				</div>
			</div>
		</a>
	)
}

// frontend/src/lib/components/Article.svelte
<script lang="ts">
	import type { ArticlePreviewOut } from 'shared/dtos/out/article-preview-out.dto';
	import { isRecent } from '$lib/utilities/is-recent.utility';
	import { ROUTES } from '$lib/configuration/routes.configuration';

	interface Props {
		article: ArticlePreviewOut;
	}

	const { article }: Props = $props();
</script>

<a
	href={ROUTES.Article(article.id)}
	class="group mx-auto block w-full max-w-100 cursor-pointer overflow-hidden transition-transform hover:-translate-y-2"
>
	<div class="relative aspect-video w-full overflow-hidden rounded-sm bg-gray-100">
		{#if isRecent(article.createdAt)}
			<div
				class="absolute top-3 left-3 z-10 rounded-sm bg-brand-red px-3 py-1 text-sm font-bold text-white"
			>
				NUEVO
			</div>
		{/if}

		<img
			loading="lazy"
			src={article.image}
			alt={article.title}
			class="h-full w-full object-cover"
		/>
	</div>

	<div class="mt-4 flex w-full flex-col gap-y-2">
		<div class="flex w-full flex-col gap-y-2">
			<h4 class="text-2xl wrap-break-word text-brand-red">
				{article.subtitle}
			</h4>

			<h3 class="line-clamp-4 font-title text-4xl wrap-break-word text-black">
				{article.title}
			</h3>

			<p class="text-[16px] wrap-break-word text-gray-900">
				{article.description}
			</p>

			<div class="mt-2 line-clamp-4 text-[18px] wrap-break-word text-gray-700">
				{article.author.name}
			</div>
		</div>
	</div>
</a>
